MAINT-36799 : Cannot edit document with onlyoffice when the space name contains special chars
exo-addons/onlyoffice pull request #64
Opened 2020-11-24 08:19 UTC by Rdidmohamedelhadi

**Problem :**  Cannot edit document with onlyoffice when the space name contains special chars .
**Solution :**  clean the name of drive.

2020-11-30 16:46 UTC, ahamdi requested changes

2020-11-30 16:46 UTC, ahamdi commented on webapp/src/main/webapp/js/onlyoffice.js
> +        const urlParams = new URLSearchParams(config.explorerUrl);
Could you check and fix the drive name directly from the portlet instead of JS ?

2020-11-30 16:52 UTC, Rdidmohamedelhadi commented on webapp/src/main/webapp/js/onlyoffice.js
> +        const urlParams = new URLSearchParams(config.explorerUrl);
ok I will do that

2020-12-01 11:06 UTC, ahamdi requested changes
Add a UT to make sure we get the drive of the file correctly

2020-12-03 14:03 UTC, ahamdi approved these changes

2020-12-03 14:04 UTC, merged

2020-12-03 14:05 UTC, ahamdi requested changes

2020-12-03 14:05 UTC, ahamdi commented on webapp/src/main/webapp/js/onlyoffice.js
> +      var drive = config.editorPage.drive;
Could you manage the case if drive is null? Dince the function getdrive may return null

2020-12-03 14:05 UTC, Rdidmohamedelhadi commented on webapp/src/main/webapp/js/onlyoffice.js
> +      var drive = config.editorPage.drive;
ok